name: getdiff

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Diff Action
      uses: technote-space/get-diff-action@v1.2.8
